trigger:
- master

pool:
  name: $(PoolName)
  vmImage: $(PoolImage)

variables:
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: PowerShell@2
  displayName: "Benchmark startup Xamarin Forms $(XamarinFormsVersion)"
  inputs:
    filePath: 'profile-android.ps1'
    arguments: "-project HelloForms/HelloForms.Android/HelloForms.Android.csproj -package com.microsoft.helloforms -configuration $(BuildConfiguration) -extra /p:USE_XAMLC=$(UseXamlc) -xamarinformsversion $(XamarinFormsVersion) -androidapi $(AndroidApi)"

- task: PowerShell@2
  displayName: "Benchmark startup Xamarin Android"
  inputs:
    filePath: 'profile-android.ps1'
    arguments: "-project HelloAndroid/HelloAndroid/HelloAndroid.csproj -package com.microsoft.helloandroid -configuration $(BuildConfiguration)"

- task: PowerShell@2
  displayName: "Benchmark startup Flutter"
  inputs:
    filePath: 'profile-android.ps1'
    arguments: "-project helloflutter -package com.microsoft.helloflutter -configuration $(BuildConfiguration)"
